package br.una.zisc.dao;
// Generated 12/11/2016 15:07:10 by Hibernate Tools 4.3.1

import java.sql.Date;

/**
 * Alerta generated by hbm2java
 */
public class Alerta implements java.io.Serializable {

    private int idalerta;
    private Usuario usuario;
    private Date loghora;
    private String longitude;
    private String latitude;
    private String bairro;
    private String cidade;
    private String estado;
    private String observacao;
    private String tipo;
    private boolean epositivo;
    private boolean statusAtivo;

    public Alerta() {
    }

    public Alerta(int idalerta, Usuario usuario, Date loghora, String longitude, String latitude, String bairro, String cidade, String estado, String observacao, String tipo, boolean epositivo, boolean statusAtivo) {
        this.idalerta = idalerta;
        this.usuario = usuario;
        this.loghora = loghora;
        this.longitude = longitude;
        this.latitude = latitude;
        this.bairro = bairro;
        this.cidade = cidade;
        this.estado = estado;
        this.observacao = observacao;
        this.tipo = tipo;
        this.epositivo = epositivo;
        this.statusAtivo = statusAtivo;
    }

    public Alerta(Usuario usuario, Date loghora, String longitude, String latitude, String bairro, String cidade, String estado, String observacao, String tipo, boolean epositivo, boolean statusAtivo) {
        this.usuario = usuario;
        this.loghora = loghora;
        this.longitude = longitude;
        this.latitude = latitude;
        this.bairro = bairro;
        this.cidade = cidade;
        this.estado = estado;
        this.observacao = observacao;
        this.tipo = tipo;
        this.epositivo = epositivo;
        this.statusAtivo = statusAtivo;
    }

    public int getIdalerta() {
        return this.idalerta;
    }

    public void setIdalerta(int idalerta) {
        this.idalerta = idalerta;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Date getLoghora() {
        return this.loghora;
    }

    public void setLoghora(Date loghora) {
        this.loghora = loghora;
    }

    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public boolean isEpositivo() {
        return this.epositivo;
    }

    public void setEpositivo(boolean epositivo) {
        this.epositivo = epositivo;
    }

    public boolean isStatusAtivo() {
        return this.statusAtivo;
    }

    public void setStatusAtivo(boolean statusAtivo) {
        this.statusAtivo = statusAtivo;
    }

}
