package br.una.zisc.dao;
// Generated 01/11/2016 20:08:24 by Hibernate Tools 4.3.1



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private int idendereco;
     private Usuario usuario;
     private String longitude;
     private String latitude;
     private String tiporesidencia;

    public Endereco() {
    }

    public Endereco(int idendereco, Usuario usuario, String longitude, String latitude, String tiporesidencia) {
       this.idendereco = idendereco;
       this.usuario = usuario;
       this.longitude = longitude;
       this.latitude = latitude;
       this.tiporesidencia = tiporesidencia;
    }
   
    public int getIdendereco() {
        return this.idendereco;
    }
    
    public void setIdendereco(int idendereco) {
        this.idendereco = idendereco;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getTiporesidencia() {
        return this.tiporesidencia;
    }
    
    public void setTiporesidencia(String tiporesidencia) {
        this.tiporesidencia = tiporesidencia;
    }




}


