package br.una.zisc.dao;
// Generated 12/11/2016 15:07:10 by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * Endereco generated by hbm2java
 */
public class Endereco implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idendereco;
    @OneToOne
    private Usuario usuario;
    private String bairro;
    private String cidade;
    private String estado;
    private String longitude;
    private String latitude;
    private String tiporesidencia;

    public Endereco() {
    }

    public Endereco(int idendereco, Usuario usuario, String bairro, String cidade, String estado, String longitude, String latitude, String tiporesidencia) {
        this.idendereco = idendereco;
        this.usuario = usuario;
        this.bairro = bairro;
        this.cidade = cidade;
        this.estado = estado;
        this.longitude = longitude;
        this.latitude = latitude;
        this.tiporesidencia = tiporesidencia;
    }

    public int getIdendereco() {
        return this.idendereco;
    }

    public void setIdendereco(int idendereco) {
        this.idendereco = idendereco;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getTiporesidencia() {
        return this.tiporesidencia;
    }

    public void setTiporesidencia(String tiporesidencia) {
        this.tiporesidencia = tiporesidencia;
    }

}
