package br.una.zisc.dao;
// Generated 12/11/2016 15:07:10 by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Seguranca generated by hbm2java
 */
public class Seguranca implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idseguranca;
    @OneToMany
    private Usuario usuario;
    private String hash;

    public Seguranca() {
    }

    public Seguranca(int idseguranca, Usuario usuario, String hash) {
        this.idseguranca = idseguranca;
        this.usuario = usuario;
        this.hash = hash;
    }

    public Seguranca(Usuario usuario, String hash) {
        this.usuario = usuario;
        this.hash = hash;
    }

    public int getIdseguranca() {
        return this.idseguranca;
    }

    public void setIdseguranca(int idseguranca) {
        this.idseguranca = idseguranca;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

}
