package br.una.zisc.dao;
// Generated 01/11/2016 20:08:24 by Hibernate Tools 4.3.1



/**
 * Seguranca generated by hbm2java
 */
public class Seguranca  implements java.io.Serializable {


     private int idseguranca;
     private Usuario usuario;
     private String hash;

    public Seguranca() {
    }

    public Seguranca(int idseguranca, Usuario usuario, String hash) {
       this.idseguranca = idseguranca;
       this.usuario = usuario;
       this.hash = hash;
    }
   
    public int getIdseguranca() {
        return this.idseguranca;
    }
    
    public void setIdseguranca(int idseguranca) {
        this.idseguranca = idseguranca;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }




}


